import {
  Key,
  Hash,
  Clock,
  UserSquare,
  BracketsCurly,
  FileCode,
  LinkSimple,
  Keyhole,
  FileText,
  TextAlignLeft,
  Palette,
  Code,
  Globe,
  ImageSquare,
  FingerprintSimple,
  Cube,
  CalendarCheck,
  BookOpen,
  BracketsAngle,
  File,
  FileMinus,
  DownloadSimple,
  SquaresFour,
  Square,
  GridFour,
  QrCode,
  TextT,
  Table,
  GitBranch,
  Tag,
  Database,
  LockKey,
  Image,
  Hexagon,
  TerminalWindow,
  ListNumbers,
  Link,
  Radio,
  Lightning,
  Hourglass,
  HandPointing,
  NotePencil,
  GlobeStand,
  Timer,
  Alarm,
  TreeStructure,
  AppWindow,
  ArrowSquareOut,
  FileLock,
  FileSearch,
  FileDotted,
  Swap,
  Equals,
  CircleHalf,
  FadersHorizontal,
  ChartLineUp,
  TextAa,
  Terminal,
  TrafficSign,
  Path,
  FileHtml,
  ShieldCheck,
  Fingerprint,
  GitDiff,
  Graph,
  ListBullets,
  Keyboard,
  Robot,
  Swatches,
  Scroll,
  CoinVertical,
  DiceSix,
  Broadcast,
  DotsSix,
  PaintBrush,
  Perspective,
  Drop,
  FrameCorners,
} from "phosphor-react";

export const navGroups = [
  {
    name: "Generators",
    items: [
      {
        path: "/",
        label: "Password",
        icon: Key,
        description: "Generate strong, random passwords.",
      },
      {
        path: "/uuid",
        label: "UUID Gen",
        icon: Hash,
        description: "Create RFC-compliant UUIDs, including bulk generation.",
      },
      {
        path: "/persona",
        label: "Persona",
        icon: UserSquare,
        description: "Quickly spin up fake personas for testing.",
      },
      {
        path: "/lorem",
        label: "Lorem",
        icon: TextAlignLeft,
        description: "Generate lorem ipsum placeholder text.",
      },
      {
        path: "/slug",
        label: "Slug",
        icon: TextT,
        description: "Convert text to URL-friendly slugs.",
      },
      {
        path: "/qr",
        label: "QR Code",
        icon: QrCode,
        description: "Generate QR codes from text/URLs.",
      },
    ],
  },
  {
    name: "CSS & Design",
    items: [
      {
        path: "/css-generator",
        label: "Drop Shadow",
        icon: Cube,
        description: "Design single and layered box shadows.",
      },
      {
        path: "/gradient-builder",
        label: "Gradient Builder",
        icon: Palette,
        description: "Build layered gradients with stop opacity controls.",
      },
      {
        path: "/text-gradient",
        label: "Text Gradient",
        icon: Drop,
        description:
          "Clip a gradient to text with background-clip using system fonts.",
      },
      {
        path: "/gradient-border",
        label: "Gradient Border",
        icon: FrameCorners,
        description:
          "Masked gradient ring so the fill can stay independently translucent.",
      },
      {
        path: "/grid",
        label: "Grid",
        icon: SquaresFour,
        description: "Experiment with CSS grid layouts.",
      },
      {
        path: "/grid-composer",
        label: "Grid Composer",
        icon: Perspective,
        description:
          "Perspective grids with repeating-linear-gradient lines and CSS transforms.",
      },
      {
        path: "/perfect-border",
        label: "Perfect Border",
        icon: Square,
        description: "Tweak border radius until it looks just right.",
      },
      {
        path: "/color",
        label: "Color",
        icon: Palette,
        description: "Explore and convert colors for your UI.",
      },
      {
        path: "/contrast",
        label: "Contrast",
        icon: CircleHalf,
        description: "Check WCAG text contrast between two colors.",
      },
      {
        path: "/clamp",
        label: "Clamp",
        icon: FadersHorizontal,
        description: "Generate fluid clamp() values from viewport bounds.",
      },
      {
        path: "/easing",
        label: "Easing",
        icon: ChartLineUp,
        description: "Edit cubic-bezier curves and copy timing CSS.",
      },
      {
        path: "/color-shades",
        label: "Shades",
        icon: Swatches,
        description:
          "OKLCH ramp from darker to lighter; copy hex table or CSS variables.",
      },
      {
        path: "/font-converter",
        label: "Font Converter",
        icon: TextT,
        description:
          "Convert TTF/OTF/WOFF/WOFF2, group families, set weights, and copy @font-face CSS.",
      },
    ],
  },
  {
    name: "Image manipulation",
    items: [
      {
        path: "/icon",
        label: "Icon",
        icon: Image,
        description: "Generate icons from text, emoji or image.",
      },
      {
        path: "/svg",
        label: "SVG",
        icon: Path,
        description: "Optimize SVG, recolor or currentColor, edit path d, build sprites.",
      },
      {
        path: "/image-composition",
        label: "Composition",
        icon: GridFour,
        description: "Compose multiple images on one canvas and export PNG or JPG.",
      },
      {
        path: "/image-editor",
        label: "Editor",
        icon: PaintBrush,
        description:
          "Greyscale, invert, and hue/saturation tweaks; download PNG or JPG.",
      },
    ],
  },
  {
    name: "Signals & spelling",
    items: [
      {
        path: "/braille",
        label: "Braille",
        icon: DotsSix,
        description:
          "Grade 1 English Braille with Unicode patterns; number sign for digits.",
      },
      {
        path: "/morse",
        label: "Morse Code",
        icon: Radio,
        description: "Encode/decode Morse with reference table.",
      },
      {
        path: "/nato",
        label: "NATO Phonetic",
        icon: Broadcast,
        description: "Spell text with ICAO words and digit names.",
      },
    ],
  },
  {
    name: "Encode / Decode",
    items: [
      {
        path: "/base64",
        label: "Base64",
        icon: FileCode,
        description: "Encode/decode text using Base64.",
      },
      {
        path: "/base64-image",
        label: "Base64 Image",
        icon: ImageSquare,
        description: "Encode/decode images using Base64.",
      },
      {
        path: "/url",
        label: "URL",
        icon: LinkSimple,
        description: "URL-encode and decode strings.",
      },
      {
        path: "/html-entity",
        label: "HTML Entity",
        icon: Code,
        description: "Convert text to/from HTML entities.",
      },
      {
        path: "/escape",
        label: "Escape/Unescape",
        icon: TerminalWindow,
        description: "Escape strings for JSON, regex, SQL, etc.",
      },
      {
        path: "/hex-converter",
        label: "Hex Converter",
        icon: Hexagon,
        description: "Convert between hex, binary, decimal, octal.",
      },
      {
        path: "/unicode",
        label: "Unicode",
        icon: TextAa,
        description:
          "Inspect graphemes, code points, UTF-8, and normalization.",
      },
    ],
  },
  {
    name: "Hashing & Security",
    items: [
      {
        path: "/hash",
        label: "Hash",
        icon: FingerprintSimple,
        description: "Create hashes for strings.",
      },
      {
        path: "/hmac",
        label: "HMAC",
        icon: Fingerprint,
        description:
          "HMAC-SHA256 or HMAC-SHA512; hex and Base64 output in the browser.",
      },
      {
        path: "/password-hash",
        label: "Password Hash",
        icon: LockKey,
        description: "Hash passwords with bcrypt.",
      },
      {
        path: "/jwt",
        label: "JWT",
        icon: Keyhole,
        description:
          "Decode, verify HS256, and create HS256/RS256 signed JWTs.",
      },
      {
        path: "/chmod",
        label: "chmod",
        icon: FileLock,
        description: "Toggle Unix rwx permissions and copy octal chmod.",
      },
    ],
  },
  {
    name: "Format & Convert",
    items: [
      {
        path: "/json",
        label: "JSON",
        icon: BracketsCurly,
        description: "Pretty-print, minify, and validate JSON.",
      },
      {
        path: "/json-editor",
        label: "JSON Editor",
        icon: TreeStructure,
        description:
          "Edit JSON in a tree: keys, values, reorder, collapse, duplicate, delete.",
      },
      {
        path: "/xml",
        label: "XML",
        icon: FileHtml,
        description: "Format, minify, and check well-formed XML in the browser.",
      },
      {
        path: "/markdown",
        label: "Markdown/HTML",
        icon: File,
        description: "Convert between Markdown and HTML.",
      },
      {
        path: "/yaml-json",
        label: "YAML/JSON",
        icon: File,
        description: "Convert between YAML and JSON.",
      },
      {
        path: "/toml-json",
        label: "TOML/JSON",
        icon: ListBullets,
        description: "Convert between TOML and JSON in the browser.",
      },
      {
        path: "/csv-json",
        label: "CSV/JSON",
        icon: Table,
        description: "Convert between CSV and JSON.",
      },
      {
        path: "/table-csv",
        label: "Table/CSV",
        icon: Table,
        description: "Convert HTML tables to CSV and CSV to HTML tables.",
      },
      {
        path: "/sql-formatter",
        label: "SQL Formatter",
        icon: Database,
        description: "Format and minify SQL queries.",
      },
      {
        path: "/sql-schema",
        label: "SQL Schema",
        icon: TreeStructure,
        description: "Drop or paste DDL to explore tables, columns, and relationships.",
      },
      {
        path: "/graphql-format",
        label: "GraphQL",
        icon: Graph,
        description: "Parse and print GraphQL documents. Validates syntax; no server.",
      },
      {
        path: "/curl-convert",
        label: "cURL → JS",
        icon: Swap,
        description: "Turn common curl commands into fetch or axios snippets.",
      },
    ],
  },
  {
    name: "Web & Config",
    items: [
      {
        path: "/meta-tags",
        label: "Meta Tags",
        icon: Tag,
        description: "Generate Open Graph and Twitter meta tags.",
      },
      {
        path: "/crontab",
        label: "Crontab",
        icon: CalendarCheck,
        description:
          "Build cron expressions, humanize them, and preview next run times.",
      },
      {
        path: "/env",
        label: ".env",
        icon: FileDotted,
        description: "Parse and edit .env files locally, then copy export.",
      },
      {
        path: "/nginx-format",
        label: "Nginx",
        icon: Terminal,
        description: "Format nginx configs and run light lint checks.",
      },
      {
        path: "/redirects",
        label: "Redirects",
        icon: TrafficSign,
        description: "Generate redirect snippets for Netlify, Vercel, and more.",
      },
      {
        path: "/csp",
        label: "CSP",
        icon: ShieldCheck,
        description:
          "Build a Content-Security-Policy header or meta tag. Empty fields are omitted.",
      },
      {
        path: "/gitignore",
        label: ".gitignore",
        icon: FileMinus,
        description: "Combine preset blocks and your own lines; duplicates removed.",
      },
      {
        path: "/robots",
        label: "Robots",
        icon: Robot,
        description:
          "Build User-agent groups and Sitemap lines; copy the file body.",
      },
    ],
  },
  {
    name: "Inspect & Analyze",
    items: [
      {
        path: "/regex",
        label: "Regex",
        icon: BracketsAngle,
        description: "Build and test regular expressions.",
      },
      {
        path: "/url-parser",
        label: "URL Parser",
        icon: Link,
        description: "Parse and build URLs with query params.",
      },
      {
        path: "/url-expand",
        label: "URL Redirects",
        icon: ArrowSquareOut,
        description:
          "Inspect redirect chains from curl output or in-browser fetch.",
      },
      {
        path: "/diff",
        label: "Diff",
        icon: GitDiff,
        description:
          "Line-based unified or side-by-side diff with optional ignore trim and case.",
      },
      {
        path: "/semver",
        label: "Semver",
        icon: Equals,
        description: "Compare versions and test npm-style semver ranges.",
      },
      {
        path: "/keycode",
        label: "Keycode",
        icon: Keyboard,
        description:
          "Focus a capture area; see key, code, which, and modifiers (keydown).",
      },
      {
        path: "/markdown-viewer",
        label: "MarkDown Viewer",
        icon: DownloadSimple,
        description: "Render Markdown for quick previews.",
      },
    ],
  },
  {
    name: "Time",
    items: [
      {
        path: "/timestamp",
        label: "Timestamp",
        icon: Clock,
        description: "Convert to/from Unix timestamps.",
      },
      {
        path: "/timezone-converter",
        label: "Timezones",
        icon: GlobeStand,
        description: "Compare the same instant across two IANA time zones.",
      },
      {
        path: "/stopwatch",
        label: "Stopwatch",
        icon: Timer,
        description: "Lap-capable stopwatch with a wide high-resolution display.",
      },
      {
        path: "/countdown",
        label: "Countdown",
        icon: Alarm,
        description: "Count down with a full-screen flash when time hits zero.",
      },
    ],
  },
  {
    name: "Reference",
    items: [
      {
        path: "/http-status",
        label: "HTTP Status",
        icon: FileText,
        description: "Look up HTTP status codes.",
      },
      {
        path: "/tailwind",
        label: "Tailwind",
        icon: BookOpen,
        description: "Quick Tailwind CSS reference.",
      },
      {
        path: "/ip",
        label: "My IP",
        icon: Globe,
        description: "Show your public IP address.",
      },
      {
        path: "/git-cheatsheet",
        label: "Git Cheatsheet",
        icon: GitBranch,
        description: "Quick reference for common Git commands.",
      },
      {
        path: "/windows-cheat-sheet",
        label: "Windows Cheat Sheet",
        icon: AppWindow,
        description:
          "Explorer paths, environment variables, shell: folders, and Run dialog commands.",
      },
      {
        path: "/ascii-table",
        label: "ASCII Table",
        icon: ListNumbers,
        description: "Look up character codes and symbols.",
      },
      {
        path: "/mime",
        label: "MIME",
        icon: FileSearch,
        description: "Look up MIME types by file extension.",
      },
      {
        path: "/local-notes",
        label: "Local Notes",
        icon: NotePencil,
        description: "Store notes in localStorage. Add and remove.",
      },
    ],
  },
  {
    name: "Pointless",
    items: [
      {
        path: "/strobo",
        label: "Strobo",
        icon: Lightning,
        description: "Flashing lights. Speed and color.",
      },
      {
        path: "/existential-timer",
        label: "Existential Timer",
        icon: Hourglass,
        description: "Counts seconds. Asks why. No answers.",
      },
      {
        path: "/click-counter",
        label: "Click Counter",
        icon: HandPointing,
        description: "Count clicks. Button moves. Pointless.",
      },
      {
        path: "/scroll-sanctifier",
        label: "Scroll sanctifier",
        icon: Scroll,
        description:
          "Scroll for ceremony, get a fake certificate. Nothing is saved.",
      },
      {
        path: "/coin-flip",
        label: "Coin flip",
        icon: CoinVertical,
        description: "Fair 50/50 coin flip. No history, no stakes.",
      },
      {
        path: "/dice",
        label: "Dice",
        icon: DiceSix,
        description: "Roll one, two, or three d6 and see the total.",
      },
    ],
  },
];
